# Generated by Django 4.2 on 2025-09-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
    ]
